name: Run API Tests
description: Run API tests Action
inputs:
  tags:
    description: Tags to run
    required: true

runs:
  using: "composite"
  steps:
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: 🫙 Cache node modules
      uses: actions/cache@v4
      id: node-modules-cache
      with:
        path: |
          api/node_modules
        key: api-modules-${{ hashFiles('api/package-lock.json') }}

    - name: 📦 Install dependencies
      shell: bash
      working-directory: ./api
      run: npm ci
      if: steps.node-modules-cache.outputs.cache-hit != 'true'

    - name: Get installed Playwright version
      id: playwright-version
      shell: bash
      working-directory: ./api
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').packages[''].devDependencies['@playwright/test'])")" >> $GITHUB_ENV

    - name: Cache playwright binaries
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: 📦🌐 Install Playwright dependencies 
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ./api
      run: npx playwright install --with-deps

    - name: Run API tests
      shell: bash
      working-directory: ./api
      run: npx playwright test --grep ${{ inputs.tags }}